import React from "react";
import { motion } from "framer-motion";
import { ArrowRight, Bot, CheckCircle2, CreditCard, MapPin, ShoppingBag, Sparkles, Truck, Utensils } from "lucide-react";
import { Link } from "react-router-dom";

const steps = [
  ["01", "Tell FoodAI what you want", "Describe a craving in plain language. Budget, mood, diet, and table size are all welcome.", <Bot />],
  ["02", "Choose a kitchen", "Compare dishes, ratings, review signals, offers, and delivery times before you decide.", <Utensils />],
  ["03", "Build your order", "Tune portions, add favourites to your cart, and see every line price before checkout.", <ShoppingBag />],
  ["04", "Track the journey", "Pay securely and follow your order from kitchen confirmation to your doorstep.", <Truck />],
];
const HowItWorks = () => <div className="min-h-screen bg-[#f7f8f4] px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><header className="rounded-[2rem] bg-[#143733] p-8 text-white shadow-xl sm:p-14"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.2em] text-lime-300">A better way to order</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">From craving to doorstep, without the guesswork.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/65">FoodExpress combines smart discovery with a beautifully simple delivery flow.</p></div></header><section className="relative mt-14 grid gap-5 md:grid-cols-2">{steps.map(([number, title, text, icon], index) => <motion.article key={number} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }} whileHover={{ y: -5 }} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-start justify-between"><span className="text-5xl font-black text-orange-200">{number}</span><div className="rounded-2xl bg-orange-50 p-3 text-orange-600">{icon}</div></div><h2 className="mt-8 text-2xl font-black">{title}</h2><p className="mt-3 max-w-md leading-7 text-slate-500">{text}</p></motion.article>)}</section><section className="mt-16 grid gap-4 border-t border-slate-200 pt-10 sm:grid-cols-3"><div className="flex gap-3"><Sparkles className="text-orange-600" /><p className="text-sm leading-6"><b className="block">Personalized by design</b><span className="text-slate-500">Recommendations improve as your tastes evolve.</span></p></div><div className="flex gap-3"><CreditCard className="text-emerald-700" /><p className="text-sm leading-6"><b className="block">Clear checkout</b><span className="text-slate-500">Secure payment and transparent totals every time.</span></p></div><div className="flex gap-3"><MapPin className="text-sky-700" /><p className="text-sm leading-6"><b className="block">Live visibility</b><span className="text-slate-500">See your order status and delivery ETA in real time.</span></p></div></section><div className="mt-12 text-center"><Link to="/discover" className="inline-flex items-center gap-2 rounded-xl bg-[#143733] px-5 py-3 font-black text-white transition hover:bg-orange-600">Try FoodAI <ArrowRight size={16} /></Link></div></div></div>;
export default HowItWorks;
