import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Heart, MessageSquareQuote, Star, ThumbsUp } from "lucide-react";
import axios from "axios";
import { API_BASE } from "../utils/api";

const Reviews = () => {
  const [summary, setSummary] = useState(null);
  useEffect(() => { axios.get(`${API_BASE}/ai/review-summary`).then(({ data }) => setSummary(data)).catch(() => {}); }, []);
  const highlights = summary?.highlights || ["Freshly prepared", "Generous portions", "Great value"];
  return <div className="min-h-screen bg-[#f7f8f4] px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl space-y-10"><header className="rounded-[2rem] bg-gradient-to-br from-orange-500 to-rose-600 p-8 text-white shadow-xl sm:p-14"><MessageSquareQuote size={38} className="text-orange-100" /><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">The good stuff, in their words.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/75">Real customer signals, distilled by FoodAI so you can choose with confidence.</p></header><section className="grid gap-6 lg:grid-cols-[280px_1fr]"><div className="rounded-3xl bg-[#143733] p-7 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-lime-300">AI review pulse</p><div className="mt-8 flex items-end gap-3"><span className="text-6xl font-black">{summary?.rating || "4.8"}</span><Star className="mb-2 fill-[#e7f55f] text-[#e7f55f]" size={24} /></div><p className="mt-3 text-sm text-white/60">From {summary?.reviewCount || "2,400"} customer signals</p><div className="mt-8 space-y-4">{(summary?.breakdown || [{ label: "Taste", value: 94 }, { label: "Portions", value: 91 }, { label: "Value", value: 88 }]).map(item => <div key={item.label}><div className="mb-1 flex justify-between text-xs font-bold"><span>{item.label}</span><span>{item.value}%</span></div><div className="h-2 rounded-full bg-white/15"><div className="h-full rounded-full bg-[#e7f55f]" style={{ width: `${item.value}%` }} /></div></div>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-orange-600">What people keep saying</p><h2 className="mt-2 text-3xl font-black">A clearer read on every meal</h2><div className="mt-7 flex flex-wrap gap-3">{highlights.map(item => <span key={item} className="rounded-full bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-800"><ThumbsUp size={14} className="mr-2 inline" />{item}</span>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2"><motion.blockquote whileHover={{ y: -3 }} className="rounded-2xl bg-orange-50 p-5 text-sm leading-7 text-slate-700">“The food arrived hot, the portions were generous, and the recommendations actually understood what I wanted.”<footer className="mt-4 flex items-center gap-2 text-xs font-black text-orange-700"><Heart size={13} /> Priya, regular customer</footer></motion.blockquote><motion.blockquote whileHover={{ y: -3 }} className="rounded-2xl bg-slate-50 p-5 text-sm leading-7 text-slate-700">“I found a new local favourite in two minutes. The review summary saved me from scrolling forever.”<footer className="mt-4 flex items-center gap-2 text-xs font-black text-slate-700"><Heart size={13} /> Arjun, FoodAI diner</footer></motion.blockquote></div></div></section></div></div>;
};
export default Reviews;
